# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload artifact jar
      uses: actions/upload-artifact@v1
      with:
        name: Arkanoid Jar
        path: out/Arkanoid-1.0.jar
  
  checkstyle:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Checkstyle Run
      run: mvn checkstyle:checkstyle
    - name: Checkstyle Upload
      uses: actions/upload-artifact@v1
      with:
        name: Checkstyle Result
        path: target/checkstyle-result.xml
      
  pmd:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Pmd Run
      run: mvn pmd:pmd
    - name: Pmd Upload
      uses: actions/upload-artifact@v1
      with:
        name: Pmd Result
        path: target/pmd.xml

  spotbugs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Spotbugs Run
      run: mvn -B compile spotbugs:spotbugs
    - name: Spotbugs Upload 
      uses: actions/upload-artifact@v2
      with:
        name: Spotbugs Result
        path: target/spotbugsXml.xml
